# Generated by Django 4.2.3 on 2024-02-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_dating_app', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=50)),
                ('language', models.CharField(default='english', max_length=50)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('preferred_pet_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_dating_app.petprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet_dating_app.owner')),
            ],
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profiles', to='pet_dating_app.owner'),
        ),
    ]
